"""Headless demo of the REAL AgentSession pipeline (no LiveKit server needed).

Uses `AgentSession.run()` -- the SDK's official API for driving a session
outside a room (it powers LiveKit's own evals). The Agent, AgentSession, the
@function_tool dispatch and the LLM are all real SDK components. The run is
text-driven, so the audio legs (STT/TTS) are not exercised here -- they run in
the live `worker.py` voice path.

This produces the transcript + tool-invocation log required by Task 1.1.

Run:
    ollama pull qwen2.5:1.5b && ollama serve
    python run_session_demo.py
"""

from __future__ import annotations

import asyncio
import logging
import os
from pathlib import Path

from dotenv import load_dotenv
from livekit.agents import AgentSession
from livekit.agents.llm import ChatMessage, FunctionCall, FunctionCallOutput
from livekit.plugins import openai

from agent import SupportAgent

load_dotenv()

HERE = Path(__file__).parent
LOG_DIR = HERE / "logs"
LOG_DIR.mkdir(exist_ok=True)
TRANSCRIPT_MD = HERE / "demo_transcript.md"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
    handlers=[
        logging.FileHandler(LOG_DIR / "session.log", mode="w", encoding="utf-8"),
        logging.StreamHandler(),
    ],
)
logger = logging.getLogger("demo")

USER_TURNS = [
    "Hi, are you a real person?",
    "What's the status of my order ORD-1001?",
    "Thanks! Can you check ORD-9999 too?",
]


async def main() -> None:
    """Drive scripted turns through a real AgentSession and log the results."""
    session = AgentSession(
        llm=openai.LLM.with_ollama(
            model=os.getenv("OLLAMA_MODEL", "qwen2.5:1.5b"),
            base_url=os.getenv("OLLAMA_URL", "http://localhost:11434") + "/v1",
            # temperature=0 makes tool-routing deterministic; without it a small
            # model intermittently skips the tool on indirect phrasings.
            temperature=0.0,
        )
    )

    # NOTE: capture_run=True makes start() await an initial agent-initiated
    # reply. Our agent waits for the user, so we start plainly and use run().
    await session.start(agent=SupportAgent())
    logger.info("AgentSession started (text-driven, no room)")

    transcript = LOG_DIR / "transcript.log"
    tool_log = LOG_DIR / "tool_invocation.log"

    tool_calls_seen = 0
    md: list[str] = [
        "# Section 1 — Real demo transcript",
        "",
        "Generated by `run_session_demo.py` driving a **real** `AgentSession` "
        "(real `SupportAgent`, real Ollama LLM, real `@function_tool` dispatch). "
        "The tool calls below are emitted by the LLM and dispatched by the SDK — "
        "our code never calls the tool itself.",
        "",
    ]

    with transcript.open("w", encoding="utf-8") as ts, tool_log.open(
        "w", encoding="utf-8"
    ) as tl:
        for turn in USER_TURNS:
            logger.info("USER: %s", turn)
            ts.write(f"USER: {turn}\n")
            md.append(f"**User:** {turn}")
            md.append("")

            result = await session.run(user_input=turn)

            for event in result.events:
                item = getattr(event, "item", None)

                if isinstance(item, FunctionCall):
                    line = f"LLM invoked tool: {item.name}(arguments={item.arguments})"
                    logger.info(line)
                    tl.write(line + "\n")
                    tool_calls_seen += 1
                    md.append(f"- 🔧 **Tool call:** `{item.name}({item.arguments})`")

                elif isinstance(item, FunctionCallOutput):
                    line = (
                        f"Tool returned: {item.name} -> {item.output} "
                        f"(is_error={item.is_error})"
                    )
                    logger.info(line)
                    tl.write(line + "\n")
                    md.append(
                        f"- 📦 **Tool output:** {item.output} "
                        f"(is_error={item.is_error})"
                    )

                elif isinstance(item, ChatMessage) and item.role == "assistant":
                    reply = (item.text_content or "").strip()
                    logger.info("AGENT: %s", reply)
                    ts.write(f"AGENT: {reply}\n\n")
                    md.append(f"- 🤖 **Assistant:** {reply}")
            md.append("")

    md.append("---")
    md.append(f"_Tool invocations observed: **{tool_calls_seen}**._")
    TRANSCRIPT_MD.write_text("\n".join(md) + "\n", encoding="utf-8")

    await session.aclose()
    logger.info("Wrote %s, %s and %s", transcript, tool_log, TRANSCRIPT_MD)
    if tool_calls_seen == 0:
        logger.warning(
            "No tool calls were emitted by the LLM -- check the system prompt "
            "and that the model supports tool-calling."
        )


if __name__ == "__main__":
    asyncio.run(main())
